### ISSUE TITLE
[Bug]: crash in the newer version 0.7.11

### ISSUE THREAD

**Issue by TheGameAlly** [ViolaFlower/Re-Console#123]
### What is the issue?

the game crashes when i press ok

### To Reproduce

1. download the latest version from modrinch (1.20.1 or 1.21.1)
2. open the game and wait everything to load
3. press ok when the loading indicator text appears

### Minecraft Version

1.21

### Re-Console Version

0.7.11

### Log

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2024-08-22 03:20:23
Description: mouseClicked event handler

java.lang.IllegalStateException: [fabric-screen-api-v1] The current screen (mod.adrenix.nostalgic.client.gui.screen.vanilla.title.NostalgicTitleScreen) has not been correctly initialised, please send this crash log to the mod author. This is usually caused by calling setScreen on the wrong thread.
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:1847)
	at net.minecraft.class_437.fabric_getRemoveEvent(class_437.java:1855)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.remove(ScreenEvents.java:115)
	at net.minecraft.class_310.handler$bnp000$fabric-screen-api-v1$onScreenRemove(class_310.java:12706)
	at net.minecraft.class_310.method_1507(class_310.java:1110)
	at wily.legacy.client.controller.SDLControllerHandler.lambda$init$3(SDLControllerHandler.java:55)
	at net.minecraft.class_1255.method_19537(class_1255.java:93)
	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:53)
	at net.minecraft.class_442.handler$dag000$legacy$added(class_442.java:1119)
	at net.minecraft.class_442.method_49589(class_442.java:319)
	at net.minecraft.class_310.method_1507(class_310.java:1130)
	at wily.legacy.client.screen.LegacyScreen.method_25419(LegacyScreen.java:27)
	at net.minecraft.class_310$Anonymous$8d03fe59a0aa4f019a514b75ee2645f4.lambda$initButtons$0(MinecraftMixin.java:228)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.ensureEventsAreInitialized(class_437.java:1847)
	at net.minecraft.class_437.fabric_getRemoveEvent(class_437.java:1855)
	at net.fabricmc.fabric.api.client.screen.v1.ScreenEvents.remove(ScreenEvents.java:115)
	at net.minecraft.class_310.handler$bnp000$fabric-screen-api-v1$onScreenRemove(class_310.java:12706)
	at net.minecraft.class_310.method_1507(class_310.java:1110)
	at wily.legacy.client.controller.SDLControllerHandler.lambda$init$3(SDLControllerHandler.java:55)
	at net.minecraft.class_1255.method_19537(class_1255.java:93)
	at wily.legacy.client.controller.SDLControllerHandler.init(SDLControllerHandler.java:53)
	at net.minecraft.class_442.handler$dag000$legacy$added(class_442.java:1119)
	at net.minecraft.class_442.method_49589(class_442.java:319)
	at net.minecraft.class_310.method_1507(class_310.java:1130)
	at wily.legacy.client.screen.LegacyScreen.method_25419(LegacyScreen.java:27)
	at net.minecraft.class_310$Anonymous$8d03fe59a0aa4f019a514b75ee2645f4.lambda$initButtons$0(MinecraftMixin.java:228)
	at net.minecraft.class_4185.method_25306(class_4185.java:96)
	at net.minecraft.class_4264.method_25348(class_4264.java:48)
	at net.minecraft.class_339.method_25402(class_339.java:141)
	at net.minecraft.class_4069.method_25402(class_4069.java:38)
	at net.minecraft.class_312.method_1611(class_312.java:107)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)

-- Affected screen --
Details:
	Screen name: ~~NULL~~
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:107)
	at net.minecraft.class_312.method_22686(class_312.java:196)
	at net.minecraft.class_1255.execute(class_1255.java:108)
	at net.minecraft.class_312.method_22684(class_312.java:196)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438)
	at com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:150)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:168)
	at net.minecraft.class_1041.method_15998(class_1041.java:303)
	at net.minecraft.class_310.method_1523(class_310.java:1307)
	at net.minecraft.class_310.method_1514(class_310.java:882)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Uptime --
Details:
	JVM uptime: 47.392s
	Wall uptime: 24.040s
	High-res time: 18.824s
	Client ticks: 289 ticks / 14.450s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2501)
	at net.minecraft.class_310.method_54580(class_310.java:949)
	at net.minecraft.class_310.method_1514(class_310.java:902)
	at net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, animatica, betterf3, bettergrass, betterpingdisplay, bobby, caffeineconfig, calcmod, capes, chat_heads, cloth-config, continuity, cubes-without-borders, cull-less-leaves, dynamic_fps, e4mc_minecraft, ears, enhancedblockentities, entity_model_features, entity_sound_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fsb-interop, immediatelyfast, indium, infinite-music, iris, legacy, libzoomer, lithium, macos_input_fixes, midnightlib, modernfix, modmenu, nochatreports, noisium, nostalgic_tweaks, nvidium, obsidianui, ok_zoomer, optigui, polytone, reeses-sodium-options, ryoamiclights, sodium, sodium-extra, sspb, threadtweak, wrench_wrapper, yet_another_config_lib_v3, yosbr

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 74690920 bytes (71 MiB) / 588251136 bytes (561 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 4600G with Radeon Graphics
	Identifier: AuthenticAMD Family 23 Model 96 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.69
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 31.0.21916.2
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 23957.06
	Virtual memory used (MiB): 19689.19
	Swap memory total (MiB): 9728.00
	Swap memory used (MiB): 612.71
	Space in storage for jna.tmpdir (MiB): available: 182520.20, total: 487499.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 182520.20, total: 487499.00
	Space in storage for io.netty.native.workdir (MiB): available: 182520.20, total: 487499.00
	Space in storage for java.io.tmpdir (MiB): available: 182520.20, total: 487499.00
	Space in storage for workdir (MiB): available: 182520.20, total: 487499.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2048M
	Fabric Mods: 
		animatica: Animatica 0.6.1+1.21
		architectury: Architectury 13.0.6
		badoptimizations: BadOptimizations 2.1.4
		betterf3: BetterF3 11.0.1
		bettergrass: FabricBetterGrass 1.0.23+1.21.1
		betterpingdisplay: Better Ping Display 1.1.1
		bobby: Bobby 5.2.3+mc1.21
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		calcmod: CalcMod 1.3.2+fabric.1.21
			clientarguments: clientarguments 1.9
			org_mariuszgromada_math_mathparser_org-mxparser: MathParser.org-mXparser 5.0.6
		capes: Capes 1.5.4+1.21
		chat_heads: Chat Heads 0.12.10
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.84
		continuity: Continuity 3.0.0-beta.5+1.21
		cubes-without-borders: Cubes Without Borders 2.1.1+1.21
		cull-less-leaves: Cull Less Leaves 1.3.0
		dynamic_fps: Dynamic FPS 3.6.3
			net_lostluma_battery: battery 1.1.0
		e4mc_minecraft: e4mc 5.1.0
			folk_sisby_kaleido-config: kaleido-config 0.3.1+1.3.1
		ears: Ears 1.4.6
		enhancedblockentities: Enhanced Block Entities 0.10.1+1.21
		entity_model_features: Entity Model Features 2.2
		entity_sound_features: Entity Sound Features 0.4
		entity_texture_features: Entity Texture Features 6.2
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.6.7
		fabric-api: Fabric API 0.102.1+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b55973446a
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bc6a
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a76a
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c6a
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a76a
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c6a
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f6a
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd96a
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b36a
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b55973446a
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.20+7f945d5b6a
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.6.0+605f22ad6a
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a76a
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+1daea2156a
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.17+16c4ae256a
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b996a
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b996a
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae066a
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd96a
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc9216a
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+780172706a
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a76a
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b36a
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df3606a
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a56a
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a56a
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c6a
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b6a
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209b6a
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+40875a936a
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c6a
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+650897126a
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209b6a
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c6a
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c6a
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b36a
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e6a
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea2156a
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b36a
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd06a
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b16a
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+565991296a
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c76a
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b55973446a
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c6a
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.17+1db1cc1f6a
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+1daea2156a
		fabric-language-kotlin: Fabric Language Kotlin 1.12.0+kotlin.2.0.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		fabricskyboxes: FabricSkyBoxes 0.7.4+mc1.21
		ferritecore: FerriteCore 7.0.0
		fsb-interop: FabricSkyBoxes Interop 1.4.0+mc1.21-build.54
		immediatelyfast: ImmediatelyFast 1.2.20+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.35+mc1.21
		infinite-music: Infinite Music 0.4.3
		iris: Iris 1.7.3+mc1.21
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		legacy: Legacy4J 1.7.2
			dev_isxander_libsdl4j: libsdl4j 3.693c75e-36
		lithium: Lithium 0.13.0
		macos_input_fixes: MacOS Input Fixes 1.7
		midnightlib: MidnightLib 1.5.8
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.2+mc1.21.1
		modmenu: Mod Menu 11.0.1
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		nochatreports: No Chat Reports 1.21-v2.8.0
		noisium: Noisium 2.3.0+mc1.21-1.21.1
		nostalgic_tweaks: Nostalgic Tweaks 2.0.0-beta.904
		nvidium: Nvidium 0.2.9-beta
		obsidianui: ObsidianUI 0.2.7+mc1.21
		ok_zoomer: Ok Zoomer 9.3.0
			libzoomer: LibZoomer 0.10.0+1.21
			wrench_wrapper: Wrench Wrapper 0.4.0
		optigui: OptiGUI 2.3.0-beta.2+1.21
			org_apache_commons_commons-text: commons-text 1.12.0
			org_ini4j_ini4j: ini4j 0.5.4
		polytone: Polytone 1.21-2.3.8
			net_objecthunter_exp4j: exp4j 0.4.8
		reeses-sodium-options: Reese's Sodium Options 1.7.3+mc1.21
		ryoamiclights: RyoamicLights 0.2.11+mc1.21.1
		simplemenu: Simple Menu 1.5
		sodium: Sodium 0.5.11+mc1.21
		sodium-extra: Sodium Extra 0.5.7+mc1.21
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		sspb: Sodium Shadowy Path Blocks 3.4.0
		threadtweak: ThreadTweak 0.1.4+mc1.21
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yosbr: YOSBR 0.1.2
	Loaded Shaderpack: (off)
	Launched Version: 1.21.1
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 24.7.1.240618, ATI Technologies Inc.
	Window size: 854x480
	GFLW Platform: win32
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, animatica, betterf3, bettergrass, betterpingdisplay, bobby, caffeineconfig, calcmod, capes, chat_heads, cloth-config, continuity, cubes-without-borders, cull-less-leaves, dynamic_fps, e4mc_minecraft, ears, enhancedblockentities, entity_model_features, entity_sound_features, entity_texture_features, entityculling, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-language-kotlin, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, fabricskyboxes, fsb-interop, immediatelyfast, indium, infinite-music, iris, legacy, libzoomer, lithium, macos_input_fixes, midnightlib, modernfix (incompatible), modmenu, nochatreports, noisium, nostalgic_tweaks, nvidium, obsidianui, ok_zoomer, optigui, polytone, reeses-sodium-options, ryoamiclights, sodium, sodium-extra, sspb, threadtweak, wrench_wrapper, yet_another_config_lib_v3 (incompatible), yosbr
	Current Language: en_us
	Locale: pt_BR
	System encoding: Cp1252
	File encoding: UTF-8
	CPU: 12x AMD Ryzen 5 4600G with Radeon Graphics

### Acknowledgement

- [X] I understand and have fully filled out the form.

**Comment by SpectralPixel** [comment]
I'm having the same issue on Fedora. The crash doesn't occur on 0.7.10.

**Comment by omo50** [comment]
I'll look into this later when I'm home. I was never dealing with an issue like this during testing for 0.7.11, if I can't reproduce I'm very unsure of what I'll do though.

**Comment by omo50** [comment]
looking into this now, weird thing is that i cant reproduce on my dev instance but i can repro on an installed version from modrinth, will keep thread updated

**Comment by omo50** [comment]
...for some reason only impacts fresh instances

**Comment by omo50** [comment]
im just gonna remove NT until i can find a better way to fix this (my time is limited atm and i cant exactly leave a version that crashes up)

**Comment by omo50** [comment]
figured out this is an issue due to modrinth app. will be readded upon the problem being fixed (hopefully) soon

**Comment by omo50** [comment]
(due to modrinth app breaking folder exports on modpacks, i should have said)
